service:
  name: hello-serverless
# app and org for use with dashboard.serverless.com
app: hello-serverless-app
org: panupongdevweb

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    host: 0.0.0.0

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  apiName: api-test
  runtime: nodejs12.x
  region: ap-southeast-1
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 3
    events:
      - http:
          method: get
          path: hello
  
  add:
    handler: add.add
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: math/add
          method: post
          cors: true